version: "3.5"
services:
  attendance-system-backend:
    container_name: attendance-system-backend
    build: 
      context: .
      dockerfile: Dockerfile
    image: attendance-system-backend
    ports:
      - "8000:8000"
    restart: always
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: <username>
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_PASSWORD: <password>
      MYSQL_DATABASE: <dbname>
    ports:
      - "3306:3306"